# CI_API_V4_URL=https://gitlab.com/api/v4
# # export CI_PROJECT_NAME=sscs-thomas-nodejs-gitlab
# # export CI_COMMIT_SHORT_SHA=2cac14a7
# # export CI_COMMIT_REF_PROTECTED=true
# # export CI_DEPENDENCY_PROXY_USER=gitlab-ci-token
# # export CI_REGISTRY=registry.gitlab.com
# # export SAST_EXCLUDED_ANALYZERS=
# # export CI_COMMIT_BRANCH=main
# # export CI_BUILD_TOKEN=[MASKED]
# export CI_DEPENDENCY_PROXY_PASSWORD=[MASKED]
# export CI_PROJECT_URL=https://gitlab.com/saemea_aquasec/sscs-thomas-nodejs-gitlab
# export CI_PIPELINE_CREATED_AT=2022-12-20T19:03:38Z
# export CI_PROJECT_VISIBILITY=private
# export FF_USE_NEW_SHELL_ESCAPE=false
# export CI_JOB_JWT=[MASKED]
# export CI_JOB_URL=https://gitlab.com/saemea_aquasec/sscs-thomas-nodejs-gitlab/-/jobs/3504379808
# export FF_NETWORK_PER_BUILD=false
# export CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX=gitlab.com:443/saemea_aquasec/dependency_proxy/containers
# export CI_REGISTRY_USER=gitlab-ci-token
# export CI_SERVER_PROTOCOL=https
# export CI_BUILD_BEFORE_SHA=8dfc2ca8533c04e7d3eeae777547ba17234efa63
# export FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY=false
# export CI_SERVER_VERSION=15.7.0-pre
# export CI_BUILD_ID=3504379808
# export GITLAB_USER_LOGIN=thl-aqua
# export GITLAB_USER_EMAIL=thomas.laubrock@aquasec.com
# export OLDPWD=/
# export CI_PROJECT_ROOT_NAMESPACE=saemea_aquasec
# export FF_SCRIPT_SECTIONS=false
# export CI_COMMIT_AUTHOR="Thomas Laubrock <thomas.laubrock@aquasec.com>"
# export CI_DISPOSABLE_ENVIRONMENT=true
# export CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
# export CI_COMMIT_TITLE=pintenv
# export CI_SERVER_TLS_CA_FILE=/builds/saemea_aquasec/sscs-thomas-nodejs-gitlab.tmp/CI_SERVER_TLS_CA_FILE
# export CI_JOB_NAME_SLUG=aqua-repo-scanning
# export CI_COMMIT_REF_NAME=main
# export CI_SERVER_VERSION_PATCH=0
# export CI_SERVER_VERSION_MINOR=7
# export DOCKER_DRIVER=overlay2
# export SAST_IMAGE_SUFFIX=
# export CI_JOB_IMAGE=gitlab/dind
# export CI_JOB_TOKEN=[MASKED]
# export SECURE_ANALYZERS_PREFIX=registry.gitlab.com/security-products
# export CI_PROJECT_ID=38639236
# export CI_RUNNER_ID=12270837
# export CI_RUNNER_REVISION=a889181a
# export FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR=false
# export CI_SERVER_VERSION_MAJOR=15
# export FF_ENABLE_BASH_EXIT_CODE_CHECK=false
# export CI_COMMIT_DESCRIPTION=
# export CI_COMMIT_MESSAGE=pintenv
# export DOCKER_TLS_CERTDIR=
# export CI_SERVER_URL=https://gitlab.com
# export CI_PROJECT_REPOSITORY_LANGUAGES=smarty,makefile,html,javascript,dockerfile
# export CI_PROJECT_TITLE=sscs-thomas-nodejs-gitlab
# export CI_DEPENDENCY_PROXY_SERVER=gitlab.com:443
# export CI_PIPELINE_ID=728167275
# export CI_BUILD_REF_NAME=main
# export CI_BUILD_REF=2cac14a7fe29140a5a1b376545321be62fe1dd20
# export CI_COMMIT_REF_SLUG=main
# export CI_PAGES_DOMAIN=gitlab.io
# export GITLAB_USER_NAME=Thomas Laubrock
# export CI_REPOSITORY_URL=https://gitlab-ci-token:[MASKED]@gitlab.com/saemea_aquasec/sscs-thomas-nodejs-gitlab.git
# export CI_BUILD_STAGE=scan_repo_code
# export CI_PROJECT_DIR=/builds/saemea_aquasec/sscs-thomas-nodejs-gitlab
# export FF_USE_DIRECT_DOWNLOAD=true
# export CI_NODE_TOTAL=1
# export CI_REGISTRY_IMAGE=registry.gitlab.com/saemea_aquasec/sscs-thomas-nodejs-gitlab
# export PWD=/builds/saemea_aquasec/sscs-thomas-nodejs-gitlab
# export CI_PAGES_URL=https://saemea_aquasec.gitlab.io/sscs-thomas-nodejs-gitlab
# export CI_PIPELINE_SOURCE=push
# export CI_SERVER_HOST=gitlab.com
# export CI_JOB_STAGE=scan_repo_code
# export FF_POSIXLY_CORRECT_ESCAPES=false
# # export #CI_PROJECT_PATH=saemea_aquasec/sscs-thomas-nodejs-gitlab
# export CI_COMMIT_BEFORE_SHA=8dfc2ca8533c04e7d3eeae777547ba17234efa63
# export GITLAB_FEATURES=elastic_search,ldap_group_sync,multiple_ldap_servers,seat_link,usage_quotas,repository_size_limit,admin_audit_log,auditor_user,custom_file_templates,custom_project_templates,db_load_balancing,default_branch_protection_restriction_in_groups,extended_audit_events,external_authorization_service_api_management,geo,ldap_group_sync_filter,object_storage,pages_size_limit,password_complexity,project_aliases,enterprise_templates,git_abuse_rate_limit,required_ci_templates,runner_maintenance_note,runner_upgrade_management
# export CI_PIPELINE_IID=1
# export CI_PIPELINE_URL=https://gitlab.com/saemea_aquasec/sscs-thomas-nodejs-gitlab/-/pipelines/728167275
# export FF_ENABLE_JOB_CLEANUP=false
# export CI_SERVER_PORT=443
# # export #GITLAB_CI=true
# export CI_RUNNER_VERSION=15.6.0~beta.186.ga889181a
# export CI_SERVER_REVISION=578b06e4192
# export SAST_EXCLUDED_PATHS="spec, test, tests, tmp"
# export CI_COMMIT_SHA=2cac14a7fe29140a5a1b376545321be62fe1dd20
# export CI_BUILDS_DIR=/builds
# export CI_CONFIG_PATH=.gitlab-ci.yml
# export CI_BUILD_NAME=aqua_repo_scanning
# export FF_CMD_DISABLE_DELAYED_ERROR_LEVEL_EXPANSION=false
# export SHLVL=1
# export CI_PROJECT_PATH_SLUG=saemea-aquasec-sscs-thomas-nodejs-gitlab
# export CI_SERVER=yes
# export FF_SKIP_NOOP_BUILD_STAGES=true
# export FF_USE_POWERSHELL_PATH_RESOLVER=false
# export CI_RUNNER_SHORT_TOKEN=J2nyww-s
# export FF_USE_IMPROVED_URL_MASKING=false
export CI=true
# export CI_JOB_STATUS=running
# export SCAN_KUBERNETES_MANIFESTS=false
# export CI_DEFAULT_BRANCH=main
# export CI_PROJECT_NAMESPACE=saemea_aquasec
# export IMAGE_TAG=1.0
# export CI_CONCURRENT_ID=153
# export CI_COMMIT_TIMESTAMP=2022-12-20T19:03:36+00:00
# export LOG=file
# export CI_PROJECT_CLASSIFICATION_LABEL=
# export CI_JOB_STARTED_AT=2022-12-20T19:04:28Z
# export FF_USE_NEW_BASH_EVAL_STRATEGY=false
# export CI_BUILD_REF_SLUG=main
# export CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX=gitlab.com:443/saemea_aquasec/dependency_proxy/containers
# export CI_RUNNER_DESCRIPTION=4-blue.shared.runners-manager.gitlab.com/default
# export FF_USE_FASTZIP=false
# export GITLAB_USER_ID=12258907
# export FF_KUBERNETES_HONOR_ENTRYPOINT=false
# export CI_JOB_ID=3504379808
# export CI_JOB_NAME=aqua_repo_scanning
# export CI_CONCURRENT_PROJECT_ID=0
# export FF_USE_WINDOWS_LEGACY_PROCESS_STRATEGY=true
# export FF_USE_DYNAMIC_TRACE_FORCE_SEND_INTERVAL=false
# export TRIGGERED_BY=PUSH
export SHLVL=1
export AQUA_SECRET=rQ2kFPHdCi2RBj8zHDLwUfEIoVezV3VxaNA
export TRIVY_RUN_AS_PLUGIN=aqua
export BUILDER_OUTPUT=/builder/outputs
export AQUA_KEY=qosNXxemu9niww7ZUUTEkY
export trivyVersion=0.34.0
export TRIVY_RUN_AS_PLUGIN=aqua
# curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v${trivyVersion}

./trivy fs --security-checks config,vuln,secret --no-progress --skip-dirs target .